version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: portfolio_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      target: development   # 👈 use dev stage in unified Dockerfile
    container_name: portfolio_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

networks:
  default:
    driver: bridge
